definitions:
  model.User:
    properties:
      age:
        type: integer
      email:
        type: string
      fullName:
        type: string
      id:
        type: integer
      phone:
        type: string
    required:
    - email
    - fullName
    type: object
info:
  contact: {}
paths:
  /users:
    delete:
      operationId: DeleteUser
      parameters:
      - description: Delete user
        in: query
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: ""
        "400":
          description: Bad Request
          schema:
            type: string
      summary: about DeleteUser
      tags:
      - Users
    get:
      operationId: SearchUsersOrdered
      parameters:
      - description: user email
        in: query
        name: email
        type: string
      - description: user phone
        in: query
        name: phone
        type: string
      - description: order by field name
        in: query
        name: orderBy
        type: string
      responses:
        "200":
          description: list of users
          schema:
            items:
              $ref: '#/definitions/model.User'
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
      summary: about SearchUsersOrdered
      tags:
      - Users
    post:
      operationId: CreateUser
      parameters:
      - description: Create user
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.User'
      responses:
        "201":
          description: User id
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            type: string
      summary: about CreateUser
      tags:
      - Users
    put:
      operationId: UpdateUser
      parameters:
      - description: Update user
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.User'
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: about UpdateUser
      tags:
      - Users
swagger: "2.0"
